kafka:
  enable: false
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      exclude: static/**,public/**
  profiles:
    active: dev
    include: swagger
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: eppt
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    database-platform: com.aseprojali.app.util.FixedPostgreSQL82Dialect
    database: postgresql
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: true
  mail:
    host: mail.example.com
    protocol: smtp
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
    jmx:
      enabled: true
    logs: # Reports Dropwizard metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds